import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // generated by FlutterFire CLI

class FirebaseService {
  static Future<void> init() async {
    // TODO: run `flutterfire configure` and uncomment firebase_options import
    await Firebase.initializeApp(
        // options: DefaultFirebaseOptions.currentPlatform,
        );
  }
}
